# Generated by Django 5.2.3 on 2025-11-08 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_negocio', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Identificador único para a URL. Ex: nome-do-salao', max_length=100, unique=True)),
                ('cor_primaria', models.CharField(default='#5CCFAC', help_text='Cor principal do tema (formato hexadecimal, ex: #FF5733)', max_length=7)),
                ('cor_secundaria', models.CharField(default='#FFFFFF', help_text='Cor secundária (ex: rosa claro #FFD1DC)', max_length=7)),
                ('tagline', models.CharField(blank=True, default='Espaço dedicado à beleza e bem-estar', max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='negocios_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.negocio')),
            ],
        ),
        migrations.CreateModel(
            name='EmpreendedorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empreendedor_profile', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='agendamentos.negocio')),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('categoria', models.CharField(choices=[('Aluguel', 'Aluguel'), ('Materiais', 'Materiais'), ('Serviços', 'Serviços'), ('Impostos', 'Impostos'), ('Salários', 'Salários'), ('Outros', 'Outros')], max_length=20)),
                ('pago', models.BooleanField(default=False)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.negocio')),
            ],
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('conteudo', models.TextField(help_text='Conteúdo do aviso. Use <li> para listas.')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Para ordenar os avisos (0 primeiro)')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='agendamentos.negocio')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('duracao_minutos', models.PositiveIntegerField(help_text='Duração do serviço em minutos')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='servicos/')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.negocio')),
                ('profissionais_que_executam', models.ManyToManyField(blank=True, related_name='servicos_oferecidos', to='agendamentos.empreendedorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado'), ('Concluído', 'Concluído')], default='Confirmado', max_length=20)),
                ('status_pagamento', models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.cliente')),
                ('empreendedor_executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos_executados', to='agendamentos.empreendedorprofile')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.servico')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_da_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('empreendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_trabalho', to='agendamentos.empreendedorprofile')),
            ],
            options={
                'ordering': ['dia_da_semana', 'hora_inicio'],
                'unique_together': {('empreendedor', 'dia_da_semana', 'hora_inicio')},
            },
        ),
    ]
