# Generated by Django 5.2.3 on 2025-11-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='dias_antecedencia_maxima',
            field=models.IntegerField(default=60, help_text='Número máximo de dias no futuro que um cliente pode agendar.'),
        ),
    ]
