# Generated by Django 5.2.3 on 2025-11-05 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='empreendedor_executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos_executados', to='agendamentos.empreendedorprofile'),
        ),
        migrations.AddField(
            model_name='servico',
            name='profissionais_que_executam',
            field=models.ManyToManyField(blank=True, related_name='servicos_oferecidos', to='agendamentos.empreendedorprofile'),
        ),
    ]
