# Generated by Django 5.2.3 on 2025-11-08 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_negocio_dias_antecedencia_maxima'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(blank=True, help_text='Ex: Feriado, Férias, Consulta Médica', max_length=100)),
                ('empreendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_bloqueados', to='agendamentos.empreendedorprofile')),
            ],
            options={
                'ordering': ['data'],
                'unique_together': {('empreendedor', 'data')},
            },
        ),
    ]
