# Generated by Django 5.2.3 on 2025-11-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_diabloqueado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendedorprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profissionais_fotos/'),
        ),
    ]
