# Generated by Django 5.2.3 on 2025-11-08 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_empreendedorprofile_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='duracao_final',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='preco_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='duracao_minutos',
            field=models.PositiveIntegerField(help_text='Duração do serviço em minutos (para 1ª vez ou troca)'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(decimal_places=2, help_text="Preço do serviço 'cheio' (para 1ª vez ou troca)", max_digits=10),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='agendamentos.negocio')),
            ],
            options={
                'unique_together': {('negocio', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='servico',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos', to='agendamentos.categoria'),
        ),
        migrations.CreateModel(
            name='PrecoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tier', models.CharField(help_text='Ex: Manutenção de 5 a 10 dias', max_length=100)),
                ('dias_min', models.PositiveIntegerField(help_text="Ex: 5 (para 'de 5 a 10 dias')")),
                ('dias_max', models.PositiveIntegerField(help_text="Ex: 10 (para 'de 5 a 10 dias')")),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracao_minutos', models.PositiveIntegerField()),
                ('servico_pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos_manutencao', to='agendamentos.servico')),
            ],
            options={
                'ordering': ['dias_min'],
            },
        ),
        migrations.AddField(
            model_name='agendamento',
            name='tier_manutencao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamentos.precomanutencao'),
        ),
    ]
