# Generated by Django 5.2.3 on 2025-11-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_agendamento_duracao_final_agendamento_preco_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Link do seu portfólio externo (Canva, site próprio, etc.)', max_length=1024, null=True),
        ),
    ]
