# Generated by Django 5.2.3 on 2025-11-12 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0007_cliente_data_nascimento'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('negocio', 'telefone')},
        ),
    ]
