# Generated by Django 5.2.6 on 2025-11-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0008_alter_cliente_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='payment_expires',
            field=models.DateTimeField(blank=True, help_text='Data e hora que o PIX expira', null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='payment_id_mp',
            field=models.CharField(blank=True, help_text='ID do pagamento gerado pelo Mercado Pago', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='payment_qrcode',
            field=models.TextField(blank=True, help_text='Código PIX Copia e Cola', null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='payment_qrcode_image',
            field=models.TextField(blank=True, help_text='Imagem Base64 do QR Code PIX', null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='valor_adiantamento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor calculado do adiantamento (se houver)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='precomanutencao',
            name='percentual_adiantamento',
            field=models.PositiveIntegerField(default=0, help_text='Porcentagem (0 a 100) a ser cobrada como adiantamento no agendamento.'),
        ),
        migrations.AddField(
            model_name='servico',
            name='percentual_adiantamento',
            field=models.PositiveIntegerField(default=0, help_text='Porcentagem (0 a 100) a ser cobrada como adiantamento no agendamento.'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('Aguardando Pagamento', 'Aguardando Pagamento'), ('Pendente', 'Pendente'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado'), ('Concluído', 'Concluído')], default='Pendente', max_length=50),
        ),
    ]
