# Generated by Django 5.2.3 on 2025-11-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0009_agendamento_payment_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado'), ('Concluído', 'Concluído')], default='Pendente', max_length=50),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status_pagamento',
            field=models.CharField(choices=[('Aguardando Pagamento', 'Aguardando Pagamento'), ('Pendente', 'Pendente'), ('Adiantamento Realizado', 'Adiantamento Realizado'), ('Pago', 'Pago'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=30),
        ),
    ]
