# Generated by Django 5.2.3 on 2025-11-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0010_alter_agendamento_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='pagamento_online_habilitado',
            field=models.BooleanField(default=False, help_text='Marque esta opção para habilitar pagamentos via Pix (adiantamento).'),
        ),
    ]
