# Generated by Django 5.2.3 on 2025-11-18 03:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0011_negocio_pagamento_online_habilitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='api_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token único para integração com n8n/Evolution API', unique=True),
        ),
    ]
